# Generated by Django 5.0.6 on 2024-07-05 01:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumberCollection', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_prime', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'numbers',
            },
        ),
    ]
