# Generated by Django 5.0.6 on 2024-07-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumberCollection', '0005_alter_number_is_prime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='is_prime',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
