# Generated by Django 5.0.6 on 2024-07-05 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumberCollection', '0006_alter_number_is_prime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNumberRelations',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NumberCollection.number')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NumberCollection.user')),
            ],
            options={
                'db_table': 'user_number_relations',
            },
        ),
    ]
