# Generated by Django 5.0.6 on 2024-07-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumberCollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
