# Generated by Django 5.0.6 on 2024-07-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumberCollection', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
